use_default_settings: true
server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "super_secret_key_for_wins_hub_searxng_2026"
search:
  formats:
    - html
    - json

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  proxies:
    all://:
      - http://tor-privoxy:8118
